apiVersion: v1
kind: ConfigMap
metadata:
  name: rdas-config
  namespace: ncba-loop
  labels:
    app: rdas
data:
  APP_PORT: "8080"
  LOG_LEVEL: "INFO"
  SOAP_ENDPOINT: "http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso"
