apiVersion: apps/v1
kind: Deployment
metadata:
  name: rdas
  namespace: ncba-loop
  labels:
    app: rdas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rdas
  template:
    metadata:
      labels:
        app: rdas
    spec:
      containers:
        - name: rdas
          image: ncba-loop/rdas:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: rdas-config
          resources:
            requests:
              memory: "768Mi"
              cpu: "500m"
            limits:
              memory: "1536Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 5
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
      restartPolicy: Always
