apiVersion: v1
kind: Service
metadata:
  name: rdas
  namespace: ncba-loop
  labels:
    app: rdas
spec:
  type: ClusterIP
  selector:
    app: rdas
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
